header_logo_url:
header_logo_text: ----------------
header_links:
  - label: Home
    link: /

  - label: About
    link: /about

  - label: 
    link: 

  - label: Student Showcase
    link: /studentshowcase
