name: gh-pages

on:
  push:
    branches: [main, setup]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the main branch
      - uses: actions/checkout@v2
        with:
          ref: 'main'
          fetch-depth: 0
      
      # Checkout the setup branch into a separate directory
      - uses: actions/checkout@v2
        with:
          ref: 'setup'
          fetch-depth: 0
          path: _setup

      # Merge files from setup and main branches
      - name: Merge setup branch files with main
        run: |
          mkdir -p deployment
          cp -r _setup/* deployment/ || true # Copy setup branch files into deployment folder
          cp -r * deployment/ || true        # Copy main branch files into deployment folder
          rm -rf deployment/_setup           # Remove the setup folder from the deployment directory

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      # Cache dependencies using the latest version of actions/cache
      - name: Cache dependencies
        uses: actions/cache@v4
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the site
      - name: Build public view
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: deployment/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
